# WebSocket SSL/TLS配置
websocket.ssl.enabled=false
websocket.ssl.keystore.path=path/to/SSl
websocket.ssl.keystore.password=sslpassword
websocket.ssl.keystore.type=type
websocket.ssl.key.password=sslpassword

# ZFile文件服务器配置
zfile.server.url=http://localhost:8081
zfile.username=stuclub-system
zfile.password=uaHZK3r3cr4Z9ei