package server.message;

public enum MessageType {
    TEXT,
    JOIN,
    LEAVE,
    SYSTEM,
    REGISTER,
    LOGIN,
    AUTH_SUCCESS,
    AUTH_FAILURE,
    UUID_AUTH,
    UUID_AUTH_SUCCESS,
    UUID_AUTH_FAILURE,
    CREATE_ROOM,
    EXIT_ROOM,
    LIST_ROOMS,
    LIST_ROOM_USERS,
    REQUEST_HISTORY,
    HISTORY_RESPONSE,
    REQUEST_LATEST_TIMESTAMP,
    LATEST_TIMESTAMP,
    REQUEST_TOKEN,
    TOKEN_RESPONSE,
    IMAGE,
    REQUEST_PRIVATE_USERS,
    PRIVATE_USERS_RESPONSE
}